# apply profile
spring:
  profiles:
    # get property from pom.xml
    active: @profile.active@
    # recommend to use group property
    group:
      "dev": devDb,devRedis,devMvc
      "test": testDb,testRedis,testMvc
      "prod": prodDb,prodRedis,prodMvc


